[workspace]
members = [
    "crates/ombrac-client",
    "crates/ombrac-server",
    "crates/ombrac",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Contributors"]
repository = "https://github.com/ombrac/ombrac"
description = "Safe, fast, small TCP tunnel using Rust"
keywords = ["proxy", "firewall"]

[workspace.dependencies]
# ombrac
ombrac = { version = "0.2.0", path = "crates/ombrac", default-features = false }
ombrac-client = { version = "0.2.0", path = "crates/ombrac-client", default-features = false }
ombrac-server = { version = "0.2.0", path = "crates/ombrac-server", default-features = false }

futures = { version = "0.3", default-features = false }
tokio = { version = "1", default-features = false }
bytes = { version = "1", default-features = false }

socks-lib = { version = "0.1", default-features = false }

# binary
clap = { version = "4", default-features = false }

# quic
s2n-quic = { version = "1", default-features = false }
aws-lc-rs = { version = "1", default-features = false }

# logging
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false }

# benches
criterion = { version = "0.5", default-features = false }

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(nightly)'] }
