[workspace]
members = [
    "crates/client",
    "crates/server",
    "crates/protocol",
]

[workspace.package]
version = "0.1.6"
edition = "2021"
license = "Apache-2.0"
authors = ["Contributors"]
repository = "https://github.com/ombrac/ombrac"

[workspace.dependencies]
# ombrac
ombrac-client = { version = "*", path = "crates/client", default-features = false }
ombrac-server = { version = "*", path = "crates/server", default-features = false }
ombrac-protocol = { version = "*", path = "crates/protocol", default-features = false }

tokio = { version = "1", default-features = false }
bytes = { version = "1", default-features = false }

socks-lib = { version = "0.1", default-features = false }

# bin
clap = { version = "4", default-features = false }

# quic
s2n-quic = { version = "1", default-features = false }
aws-lc-rs = { version = "1", default-features = false }

# dns
hickory-resolver = { version = "0.24", default-features = false }

# logging
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false }

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(nightly)'] }
