[package]
name = "ombrac-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { version = "1", default-features = false }
tokio = { version = "1",  features = ["rt", "net", "io-util"], default-features = false }
