[package]
name = "ombrac"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
repository.workspace = true
description.workspace = true
readme = "../../README.md"

[features]
default = []
datagram = ["ombrac-transport/datagram"]

[dependencies]
ombrac-transport = { workspace = true }

bytes = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "net"] }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
futures = { workspace = true, features = ["alloc"] }

[lints]
workspace = true
